language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
node_js:
  - "node"
  - "9"
cache:
  directories:
    - node_modules
install:
  - npm install -g polymer-cli
  - npm install -g firebase-tools
  - npm install
script:
  - cd weather-station-app/
  - polymer install -v
  - cd ..
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "1/jMEfYIhv7ST_QnIEKRWi8BYlNHgWN1ASxF1xWvoQs5DJ7YnxdnBgroEsdG-3oVVD"