language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "node"
  - "6"
cache:
  directories:
    - node_modules
install:
  - npm install -g polymer-cli
  - npm install
  - polymer install
deploy:
  provider: firebase
  token:
    secure: "1/jMEfYIhv7ST_QnIEKRWi8BYlNHgWN1ASxF1xWvoQs5DJ7YnxdnBgroEsdG-3oVVD"